spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 95081200axxy
    url: jdbc:mysql://localhost:3306/ordersystem?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
#    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
server:
    servlet:
      context-path: /os